name: Build
run-name: Building repository

on:
  push:
    paths:
      - src/**
      - '**/*gradle*'
    branches:
      - main
      - dev
      - release/**
      - feature/**
  pull_request:
    paths:
      - src/**
      - '**/*gradle*'
    branches:
      - main
      - dev
      - release/**
      - feature/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      fabric_version: ${{steps.build_vars.outputs.fabric_version}}
      minecraft_version: ${{steps.build_vars.outputs.minecraft_version}}
      archive_name: ${{steps.build_vars.outputs.archive_name}}
      current_version: ${{steps.build_vars.outputs.current_version}}
      new_release: ${{steps.build_vars.outputs.new_release}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: export build variables
        id: build_vars
        run: |
          grep -E "^((fabric|minecraft)?_?version|archive_name|cloth_config)=" gradle.properties >> "$GITHUB_OUTPUT"
          sed -E 's/ {2,}//; s/= /=/; s/ /_/' .nyx-summary >> $GITHUB_OUTPUT

      - name: Append build variables to Summary
        run: |
          echo "
          <table>
          <tr><td align="center">
          <h3 align="center" > Dependencies: </h3>
          
          | Minecraft Version                               | Fabric Version                               | Cloth Config                               |
          |:-----------------------------------------------:|:--------------------------------------------:|:------------------------------------------:|
          | ${{steps.build_vars.outputs.minecraft_version}} | ${{steps.build_vars.outputs.fabric_version}} | ${{steps.build_vars.outputs.cloth_config}} |
          
          </td></tr>
          <tr><td align="center">
          <h3 align="center" > Artifacts and Versioning data: </h3>
          
          | Main Artifact                                                                                | version                                       | branch                               | bump                               |
          |:--------------------------------------------------------------------------------------------:|:---------------------------------------------:|:------------------------------------:|:----------------------------------:|
          | ${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}.jar | ${{steps.build_vars.outputs.current_version}} | ${{steps.build_vars.outputs.branch}} | ${{steps.build_vars.outputs.bump}} |
          
          </td></tr>
          </table>
          
          
          " >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}
          path: build/libs/${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}.jar
          if-no-files-found: 'error'
          overwrite: 'true'

  tagging:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Update Tags
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs:
      - build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{needs.build.outputs.archive_name}}-${{needs.build.outputs.current_version}}

      - name: Release Tag
        if: needs.build.outputs.new_release == 'true'
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{github.ref_name != 'main'}}
          make_latest: ${{github.ref_name == 'main'}}
          tag_name: ${{needs.build.outputs.current_version}}
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ${{needs.build.outputs.archive_name}}-${{needs.build.outputs.current_version}}.jar

      - name: Delete Older Release candidates
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: -rc.
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete Older Beta Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: -beta.
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete Older Alpha Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: -alpha.
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}