name: Build
run-name: Building repository

on:
  push:
    paths:
      - src
  workflow_dispatch:

jobs:
  versioning:
    name: Computing version
    runs-on: ubuntu-latest
    outputs:
      SemVer: ${{steps.gitversion.outputs.semVer}}

    steps:
      - name: Checkout History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: ".github/gitVersion.yml"

      - name: print outputs
        run: echo ${{toJSON(steps.gitversion.outputs)}}

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: versioning
    outputs:
      fabric_version: ${{steps.build_vars.outputs.fabric_version}}
      minecraft_version: ${{steps.build_vars.outputs.minecraft_version}}
      archive_name: ${{steps.build_vars.outputs.archive_name}}

      update-sha: ${{steps.bump_remote.outputs.commit-sha}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Update properties file
        id: version_updater
        run: |
          echo old_version=$(sed -n 's/^version=\(.*\)/\1/p' gradle.properties) >> "$GITHUB_OUTPUT"
          sed -i 's/\(^version=\).*/\1${{jobs.versioning.outputs.SemVer}}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: export build variables
        id: build_vars
        run: |
          grep -E "^((fabric|minecraft)?_?version|archive_name)=" gradle.properties >> "$GITHUB_OUTPUT"

      - name: Append build variables to Summary
        run: |
          echo "
          | archive_name                               | Version                               | minecraft_version                               | fabric_version                               |
          |:------------------------------------------:|:-------------------------------------:|:-----------------------------------------------:|:--------------------------------------------:|
          | ${{steps.build_vars.outputs.archive_name}} | ${{steps.build_vars.outputs.version}} | ${{steps.build_vars.outputs.minecraft_version}} | ${{steps.build_vars.outputs.fabric_version}} |
          " >> $GITHUB_STEP_SUMMARY

      - name: check versions
        if: steps.build_vars.outputs.version != needs.versioning.outputs.SemVer
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Version mismatch!')
            process.exit()

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build_vars.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}
          path: build/libs/${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.version}}.jar
          if-no-files-found: 'error'
          overwrite: 'true'

      - name: Bump version
        id: bump_remote
        uses: test-room-7/action-update-file@v1
        with:
          file-path: gradle.properties
          commit-msg: >
            chore(gradle): update version to ${{needs.versioning.outputs.SemVer}}
            
            
            Updated the version number from ${{steps.version_updater.outputs.old_version}} 
            to ${{needs.versioning.outputs.SemVer}} in the gradle.properties file to reflect 
            the latest release.
          github-token: ${{github.token}}
          branch: ${{github.ref_name}}

  tagging:
    name: Tag release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs:
      - versioning
      - build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{needs.build.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          draft: true
          tag_name: v${{needs.versioning.outputs.SemVer}}
          generate_release_notes: true
          fail_on_unmatched_files: true
          target_commitish: ${{needs.build.outputs.update-sha}}
          files: ${{needs.build.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}.jar



