name: Build & Test
run-name: Building repository
on: [ push, workflow_call ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      fabric_version: ${{steps.var_setup.outputs.fabric_version}}
      minecraft_version: ${{steps.var_setup.outputs.minecraft_version}}
      mod_version: ${{steps.var_setup.outputs.mod_version}}
      archive_base_name: ${{steps.var_setup.outputs.archive_base_name}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: setup env variables
        id: var_setup
        run: |
          grep -E "(fabric_version=)|(minecraft_version=)|(mod_version=)|(archive_base_name=)" gradle.properties >> "$GITHUB_OUTPUT"
      - name: check env variables
        run: |
          echo "
          | OUTPUTS           | VALUES                                          |
          |:-----------------:|:-----------------------------------------------:|
          | fabric_version    | ${{steps.var_setup.outputs.fabric_version}}     |
          | minecraft_version | ${{steps.var_setup.outputs.minecraft_version}}  |
          | mod_version       | ${{steps.var_setup.outputs.mod_version}}        |
          | archive_base_name | ${{steps.var_setup.outputs.archive_base_name}}  |
          " >> $GITHUB_STEP_SUMMARY
      - name: remame output file as build preview
        run: cp -T build/libs/${{steps.var_setup.outputs.archive_base_name}}-${{steps.var_setup.outputs.mod_version}}.jar ${{steps.var_setup.outputs.archive_base_name}}-${{steps.var_setup.outputs.mod_version}}-build.${{github.run_number}}.jar
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.var_setup.outputs.archive_base_name}}-${{steps.var_setup.outputs.mod_version}}-build.${{github.run_number}}
          path: ${{steps.var_setup.outputs.archive_base_name}}-${{steps.var_setup.outputs.mod_version}}-build.${{github.run_number}}.jar
          if-no-files-found: 'error'
          overwrite: 'true'
  test:
    name: Runtime test
    runs-on: ubuntu-latest
    needs: build
    env:
      fabric_version: ${{needs.build.outputs.fabric_version}}
      minecraft_version: ${{needs.build.outputs.minecraft_version}}
      mod_version: ${{needs.build.outputs.mod_version}}
      archive_base_name: ${{needs.build.outputs.archive_base_name}}
    steps:
      - name: Download dependency mods
        run: |
          curl --create-dirs -O --output-dir run/mods https://cdn.modrinth.com/data/b8Q0BxnV/versions/OH74ACY1/dimdoors-5.4.1-fabric.jar
          curl --create-dirs -O --output-dir run/mods https://cdn.modrinth.com/data/9s6osm5g/versions/2xQdCMyG/cloth-config-11.1.136-fabric.jar
          curl --create-dirs -O --output-dir run/mods https://cdn.modrinth.com/data/lhGA9TYQ/versions/WbL7MStR/architectury-9.2.14-fabric.jar
      - name: Download main mod artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{env.archive_base_name}}-${{env.mod_version}}-build.${{github.run_number}}
          path: run/mods
      - name: Mc-Runtime-Test
        uses: 3arthqu4ke/mc-runtime-test@2.4.0
        with:
          mc: ${{env.minecraft_version}}
          modloader: 'fabric'
          regex: '.*fabric.*'
          java: '17'
          mc-runtime-test: 'fabric'
          fabric-api: ${{env.fabric_version}}
          hmc-version: '2.3.0'