name: Build
run-name: Building repository through Gradle
on: [ push, workflow_call ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build
      - name: get mod and game versions
        run: |
          grep -E "(minecraft_version)|(mod_version=)|(archives_base_name=)" gradle.properties >> "$GITHUB_ENV"
      - name: print versions
        run: |
          echo Minecraft version: ${{env.minecraft_version}}
          echo Mod version: ${{env.mod_version}}
          echo Archive base name: ${{env.archives_base_name}}
