name: Build
run-name: Building repository

on:
  push:
    paths:
      - src/**
      - build.gradle
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle
      - gradle
    branches:
      - main
      - dev
      - release/**
  pull_request:
    paths:
      - src/**
      - build.gradle
      - gradle.properties
      - gradlew
      - gradlew.bat
      - settings.gradle
      - gradle
    branches:
      - main
  workflow_dispatch:

jobs:
  versioning:
    name: Computing version
    runs-on: ubuntu-latest
    outputs:
      SemVer: ${{steps.gitversion.outputs.semVer}}

    steps:
      - name: Checkout History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0                # fetch the whole repo history

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: '6.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v3.0.0
        with:
          useConfigFile: true
          configFilePath: ".github/gitVersion.yml"

      - name: print outputs
        run: echo '${{toJSON(steps.gitversion.outputs)}}'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: versioning
    permissions:
      contents: write
      pull-requests: write
    outputs:
      fabric_version: ${{steps.build_vars.outputs.fabric_version}}
      minecraft_version: ${{steps.build_vars.outputs.minecraft_version}}
      archive_name: ${{steps.build_vars.outputs.archive_name}}

      update-sha: ${{steps.bump_remote.outputs.pull-request-head-sha}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Update properties file
        id: version_updater
        run: |
          echo old_version=$(sed -n 's/^version=\(.*\)/\1/p' gradle.properties) >> "$GITHUB_OUTPUT"
          sed -i 's/\(^version=\).*/\1${{needs.versioning.outputs.SemVer}}/' gradle.properties

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: export build variables
        id: build_vars
        run: |
          grep -E "^((fabric|minecraft)?_?version|archive_name)=" gradle.properties >> "$GITHUB_OUTPUT"

      - name: Append build variables to Summary
        run: |
          echo "
          | archive_name                               | Version                               | minecraft_version                               | fabric_version                               |
          |:------------------------------------------:|:-------------------------------------:|:-----------------------------------------------:|:--------------------------------------------:|
          | ${{steps.build_vars.outputs.archive_name}} | ${{steps.build_vars.outputs.version}} | ${{steps.build_vars.outputs.minecraft_version}} | ${{steps.build_vars.outputs.fabric_version}} |
          " >> $GITHUB_STEP_SUMMARY

      - name: check version mismatch
        if: steps.build_vars.outputs.version != needs.versioning.outputs.SemVer
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Version mismatch!')
            process.exit()

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build_vars.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}
          path: build/libs/${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.version}}.jar
          if-no-files-found: 'error'
          overwrite: 'true'

      - name: Bump version
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        id: bump_remote
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            gradle.properties
          commit-message: >
            chore(gradle): update version to ${{needs.versioning.outputs.SemVer}}
            
            
            Updated the version number from ${{steps.version_updater.outputs.old_version}} 
            to ${{needs.versioning.outputs.SemVer}} in the gradle.properties file to reflect 
            the latest release.
          branch: release/${{needs.versioning.outputs.SemVer}}
          title: 'Bump Version'
          body: >
            Updated the version number from ${{steps.version_updater.outputs.old_version}} 
            to ${{needs.versioning.outputs.SemVer}} in the gradle.properties file to reflect 
            the latest release.
            
            
            Automated changes by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action
          assignees: LizzieSpace
          reviewers: LizzieSpace

  tagging:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Tag release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs:
      - versioning
      - build

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{needs.build.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{github.ref_name != 'main'}}
          make_latest: ${{github.ref_name == 'main'}}
          tag_name: v${{needs.versioning.outputs.SemVer}}
          generate_release_notes: true
          fail_on_unmatched_files: true
          target_commitish: ${{needs.build.outputs.update-sha}}
          files: ${{needs.build.outputs.archive_name}}-${{needs.versioning.outputs.SemVer}}.jar

      - name: Delete Older Beta Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: beta
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Delete Older Alpha Releases
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: alpha
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}





