name: Build
run-name: Building repository

on:
  push:
    paths:
      - src/**
      - '**/*gradle*'
    branches:
      - main
      - dev
      - release/**
      - feature/**
    tags_ignore:
      - v0.*

  pull_request:
    paths:
      - src/**
      - '**/*gradle*'
    branches:
      - main
      - dev
      - release/**
      - feature/**
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      fabric_version: ${{steps.build_vars.outputs.fabric_version}}
      minecraft_version: ${{steps.build_vars.outputs.minecraft_version}}
      archive_name: ${{steps.build_vars.outputs.archive_name}}
      current_version: ${{steps.build_vars.outputs.current_version}}
      previous_version: ${{steps.build_vars.outputs.previous_version}}
      new_release: ${{steps.build_vars.outputs.new_release}}
      new_version: ${{steps.build_vars.outputs.new_version}}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        env:
          GITHUB_TOKEN: ${{github.token}}
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: export build variables
        id: build_vars
        run: |
          grep -E "^((fabric|minecraft)?_?version|archive_name|cloth_config)=" gradle.properties >> "$GITHUB_OUTPUT"
          sed -E 's/ {2,}//; s/= /=/; s/ /_/' .nyx-summary >> $GITHUB_OUTPUT

      - name: Append build variables to Summary
        run: |
          echo "
          <table>
          <tr><td align="center">
          <h3 align="center" > Dependencies: </h3>
          
          | Minecraft Version                               | Fabric Version                               | Cloth Config                               |
          |:-----------------------------------------------:|:--------------------------------------------:|:------------------------------------------:|
          | ${{steps.build_vars.outputs.minecraft_version}} | ${{steps.build_vars.outputs.fabric_version}} | ${{steps.build_vars.outputs.cloth_config}} |
          
          </td></tr>
          <tr><td align="center">
          <h3 align="center" > Artifacts and Versioning data: </h3>
          
          | Main Artifact                                                                                | version                                       | branch                               | bump                               |
          |:--------------------------------------------------------------------------------------------:|:---------------------------------------------:|:------------------------------------:|:----------------------------------:|
          | ${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}.jar | ${{steps.build_vars.outputs.current_version}} | ${{steps.build_vars.outputs.branch}} | ${{steps.build_vars.outputs.bump}} |
          
          </td></tr>
          </table>
          
          
          " >> $GITHUB_STEP_SUMMARY

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}
          path: build/libs/${{steps.build_vars.outputs.archive_name}}-${{steps.build_vars.outputs.current_version}}.jar
          if-no-files-found: 'error'
          overwrite: 'true'

  release:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    name: Update Tags
    runs-on: ubuntu-latest
    permissions:
      contents: write

    needs:
      - build

    steps:
      - name: Generate CHANGELOG
        if: needs.build.outputs.new_version == 'true'
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          fromTag: ${{ needs.build.outputs.current_version }}
          toTag: ${{ needs.build.outputs.previous_version }}
          excludeTypes: 'build,docs,other,style,ci'
          writeToFile: false
          useGitmojis: false
          reverseOrder: true

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{needs.build.outputs.archive_name}}-${{needs.build.outputs.current_version}}

      - name: Release new Tag
        if: needs.build.outputs.new_release == 'true' && needs.build.outputs.new_version == 'true'
        uses: softprops/action-gh-release@v2.0.8
        with:
          prerelease: ${{github.ref_name != 'main'}}
          make_latest: ${{github.ref_name == 'main'}}
          tag_name: ${{needs.build.outputs.current_version}}
          body: |
            Release ${{needs.build.outputs.current_version}}

            ${{steps.changelog.outputs.changes}}
            
            ---

          generate_release_notes: true
          fail_on_unmatched_files: true
          files: ${{needs.build.outputs.archive_name}}-${{needs.build.outputs.current_version}}.jar

      - name: Update "latest" tag
        if: needs.build.outputs.new_release == 'true' && needs.build.outputs.new_version == 'true' && github.ref_name == 'main'
        uses: IsaacShelton/update-existing-release@v1.3.4
        with:
          token: ${{github.token}}
          message: Release ${{needs.build.outputs.current_version}}
          body: |
            Release ${{needs.build.outputs.current_version}}
            
            ${{steps.changelog.outputs.changes}}
          release: "Latest"
          tag: "latest"
          replace: true
          files: ${{needs.build.outputs.archive_name}}-${{needs.build.outputs.current_version}}.jar

  removal:
    name: remove older releases
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        tag_pattern:
          - rc
          - beta
          - alpha

    steps:
      - name: Delete Release candidates
        uses: s00d/delete-older-releases@0.2.1
        with:
          keep_latest: 3
          delete_tag_pattern: "-${{matrix.tag_pattern}}."
          delete_type: prerelease
          delete_tags: true
          delete_branch: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ github.token }}
